# Generated by Django 5.1.2 on 2025-10-31 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do tipo de animal (ex: Cachorro, Gato, Pássaro)', max_length=50, unique=True)),
                ('icone', models.CharField(blank=True, help_text='Emoji ou ícone representando o tipo (ex: 🐶, 🐱, 🐦)', max_length=50)),
                ('ativo', models.BooleanField(default=True, help_text='Define se este tipo está ativo no sistema')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Animal',
                'verbose_name_plural': 'Tipos de Animais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da raça (ex: Labrador, Persa, Canário)', max_length=100)),
                ('observacoes_manejo', models.TextField(blank=True, help_text='Observações sobre cuidados e manejo específicos desta raça')),
                ('ativo', models.BooleanField(default=True, help_text='Define se esta raça está ativa no sistema')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_animal', models.ForeignKey(help_text='Tipo de animal ao qual esta raça pertence', on_delete=django.db.models.deletion.PROTECT, related_name='racas', to='pets.tipoanimal')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
                'ordering': ['tipo_animal', 'nome'],
                'unique_together': {('tipo_animal', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do pet', max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('I', 'Indefinido')], default='I', help_text='Sexo do animal', max_length=1)),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento do animal', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Define se este animal está ativo no sistema')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações gerais sobre o animal')),
                ('proprietario', models.ForeignKey(help_text='Usuário proprietário do animal', on_delete=django.db.models.deletion.CASCADE, related_name='animais', to=settings.AUTH_USER_MODEL)),
                ('raca', models.ForeignKey(help_text='Raça do animal', on_delete=django.db.models.deletion.PROTECT, related_name='animais', to='pets.raca')),
                ('tipo_animal', models.ForeignKey(help_text='Tipo do animal', on_delete=django.db.models.deletion.PROTECT, related_name='animais', to='pets.tipoanimal')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['-criado_em'],
                'unique_together': {('proprietario', 'nome')},
            },
        ),
    ]
