version: '3.9'

services:
  web:
    build: ./django
    container_name: django_petshop
    command: sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    env_file:
      - ./django/.env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_petshop
    restart: always
    environment:
      POSTGRES_DB: petshopdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
