# Generated by manual creation on 2025-11-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(
                choices=[
                    ('ADMIN', 'Administrador'),
                    ('CLIENTE', 'Cliente'),
                    ('FUNCIONARIO', 'Funcionário'),
                    ('VETERINARIO', 'Veterinário')
                ],
                default='CLIENTE',
                max_length=20,
                verbose_name='Tipo de Usuário'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='crmv',
            field=models.CharField(
                blank=True,
                help_text='Número do Conselho Regional de Medicina Veterinária',
                max_length=20,
                null=True,
                verbose_name='CRMV'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='especialidade',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Especialidade'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name='Telefone'
            ),
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
