# Generated by Django 5.1.2 on 2025-11-17 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(help_text='Data e hora da consulta', verbose_name='Data e Hora')),
                ('tipo', models.CharField(choices=[('CONSULTA', 'Consulta de Rotina'), ('RETORNO', 'Retorno'), ('EMERGENCIA', 'Emergência'), ('CIRURGIA', 'Cirurgia'), ('VACINACAO', 'Vacinação'), ('EXAME', 'Exame')], default='CONSULTA', max_length=20, verbose_name='Tipo de Atendimento')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('FALTOU', 'Paciente Faltou')], default='AGENDADA', max_length=20, verbose_name='Status')),
                ('motivo', models.TextField(help_text='Descrição do motivo do atendimento', verbose_name='Motivo da Consulta')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre o agendamento', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(help_text='Animal que será atendido', on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='pets.animal', verbose_name='Animal')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('veterinario', models.ForeignKey(help_text='Veterinário responsável pelo atendimento', limit_choices_to={'user_type': 'VETERINARIO'}, on_delete=django.db.models.deletion.PROTECT, related_name='consultas_veterinario', to=settings.AUTH_USER_MODEL, verbose_name='Veterinário')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('AGENDAMENTO', 'Agendamento Criado'), ('CONFIRMACAO', 'Consulta Confirmada'), ('INICIO_ATENDIMENTO', 'Atendimento Iniciado'), ('PRONTUARIO_CRIADO', 'Prontuário Criado'), ('PRONTUARIO_ATUALIZADO', 'Prontuário Atualizado'), ('RECEITA_ADICIONADA', 'Receita Adicionada'), ('CANCELAMENTO', 'Consulta Cancelada'), ('OBSERVACAO', 'Observação Adicionada')], max_length=30, verbose_name='Ação')),
                ('descricao', models.TextField(help_text='Detalhes da ação realizada', verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='consultas.consulta', verbose_name='Consulta')),
                ('usuario', models.ForeignKey(help_text='Usuário que realizou a ação', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Consulta',
                'verbose_name_plural': 'Históricos de Consultas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso do animal em quilogramas', max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura corporal em graus Celsius', max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('frequencia_cardiaca', models.IntegerField(blank=True, help_text='Batimentos por minuto', null=True, verbose_name='Frequência Cardíaca (bpm)')),
                ('frequencia_respiratoria', models.IntegerField(blank=True, help_text='Respirações por minuto', null=True, verbose_name='Frequência Respiratória (rpm)')),
                ('anamnese', models.TextField(help_text='História clínica e queixas do animal', verbose_name='Anamnese')),
                ('exame_fisico', models.TextField(help_text='Achados do exame físico', verbose_name='Exame Físico')),
                ('diagnostico', models.TextField(help_text='Diagnóstico médico veterinário', verbose_name='Diagnóstico')),
                ('tratamento', models.TextField(help_text='Plano de tratamento recomendado', verbose_name='Tratamento')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('consulta', models.OneToOneField(help_text='Consulta relacionada a este prontuário', on_delete=django.db.models.deletion.PROTECT, related_name='prontuario', to='consultas.consulta', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(help_text='Nome do medicamento prescrito', max_length=200, verbose_name='Medicamento')),
                ('dosagem', models.CharField(help_text='Dosagem do medicamento', max_length=100, verbose_name='Dosagem')),
                ('frequencia', models.CharField(help_text='Frequência de administração', max_length=100, verbose_name='Frequência')),
                ('duracao', models.CharField(help_text='Duração do tratamento', max_length=100, verbose_name='Duração')),
                ('via_administracao', models.CharField(choices=[('ORAL', 'Oral'), ('TOPICA', 'Tópica'), ('INJETAVEL_IM', 'Injetável - Intramuscular'), ('INJETAVEL_IV', 'Injetável - Intravenosa'), ('INJETAVEL_SC', 'Injetável - Subcutânea'), ('OCULAR', 'Ocular'), ('AURICULAR', 'Auricular'), ('OUTRA', 'Outra')], default='ORAL', max_length=50, verbose_name='Via de Administração')),
                ('instrucoes', models.TextField(blank=True, help_text='Instruções adicionais para o uso do medicamento', verbose_name='Instruções Especiais')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='consultas.prontuario', verbose_name='Prontuário')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['medicamento'],
            },
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['data_hora', 'veterinario'], name='consultas_c_data_ho_04a0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['animal', 'data_hora'], name='consultas_c_animal__c784e4_idx'),
        ),
    ]
